### ISSUE TITLE
cant import

### ISSUE THREAD

**Issue by machinexa2** [jmcarp/robobrowser#104] opened 2021-09-18 17:49 UTC
root@kali-linux:~# python3
Python 3.9.7 (default, Sep  3 2021, 06:18:44)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import robobrowser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/usr/local/lib/python3.9/dist-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/lib/python3/dist-packages/werkzeug/__init__.py)
>>>
root@kali-linux:~# pip install cached_property
Requirement already satisfied: cached_property in /usr/lib/python3/dist-packages (1.5.2)
root@kali-linux:~# python3
Python 3.9.7 (default, Sep  3 2021, 06:18:44)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import robobrowser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/robobrowser/__init__.py", line 3, in <module>
    from .browser import RoboBrowser
  File "/usr/local/lib/python3.9/dist-packages/robobrowser/browser.py", line 8, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (/usr/lib/python3/dist-packages/werkzeug/__init__.py)
>>>
root@kali-linux:~#

**Comment by bobpaul** [comment] 2022-02-24 14:02
Duplicate of #93

**Closed** 2022-06-07 16:49 UTC
